### ISSUE TITLE
Withdrawal system for BTC has flaws

### ISSUE THREAD

**Issue by IvadOnerom** [blinktrade/blinktrade.github.io#11]
I requested a withdrawal of 0,46280023 BTC from my account (ivadonerom@gmail.com) at https://bitcambio.blinktrade.com . However, when I tried to check the status of the transfer on http://live.blockcypher.com/, the following message appeared: transaction doesn't exist. I contacted support and they said everything was ok. I insisted on it and then they recognized the mistake. I've opened the requests 44763 (in 21/12/2017) (this one with screenshots showing the issue) and 45336 and still they haven't analysed the issue or returned my BTC.

**Comment by cesardeazevedo** [comment]
Hi, sorry for didn't see your issue, it was just on the wrong place 😅, anything related to your account should be on the bitcambio support https://bitcambiohelp.zendesk.com/hc/pt-br

Thank you.
