### ISSUE TITLE
Menu hamburguer

### ISSUE THREAD

**Issue by rands0n** [blinktrade/blinktrade.github.io#4]
O que acha do menu ser um hamburguer ao lado direito. Quando o usuário clicar ele mostra o menu abaixo.

Acho que dessa forma melhorariamos o espaço para o slide.

![screenshot from 2014-10-20 11 15 50](https://cloud.githubusercontent.com/assets/4191734/4703583/1f7b0dee-586c-11e4-8522-49f24e54349d.png)

**Comment by cesardeazevedo** [comment]
feito na nova landing 444a5da427fc7251f974ad404466c61083cdb347
